"""Differentiable Pressurised Hydraulic Model (dPHM) primitives."""

from .autograd_checks import assert_finite_gradients
from .diagnostics import SolveFailureReason, SolveResult, classify_failure
from .feasibility import FeasibilityResult, check_feasibility
from .fixtures import (
    make_branch_network,
    make_pump_network,
    make_single_loop_network,
)
from .hazen_williams import hazen_williams_head_loss
from .large_fixtures import make_grid_network
from .incidence import cached_incidence_matrix, incidence_matrix, node_flow_balance
from .inp_import_quality_report import (
    EpanetImportQualityReport,
    EpanetImportQualitySectionReport,
    EpanetImportQualitySurrogateReport,
    build_import_quality_report,
    load_inp_import_quality_report,
)
from .inp_io import (
    EDGE_SURROGATE_KIND_PRV_FIXED_HEAD,
    EDGE_SURROGATE_KIND_TCV_MINOR_LOSS,
    EDGE_SURROGATE_SEVERITY_INFO,
    EDGE_SURROGATE_SEVERITY_LIMITATION,
    EDGE_SURROGATE_SEVERITY_WARNING,
    EpanetControlKind,
    EpanetControlRuleDiagnostic,
    EpanetEdgeSurrogateDiagnostic,
    EpanetEmitterDemandDiagnostic,
    EpanetIgnoredSectionDiagnostic,
    EpanetImportDiagnostics,
    EpanetImportDiagnosticsSummary,
    EpanetPatternEnergyDiagnostic,
    EpanetStatusDiagnostic,
    EpanetWaterQualityDiagnostic,
    fit_power_pump_surrogate,
    fit_pump_head_curve,
    fit_tcv_resistance_surrogate,
    load_inp_diagnostics,
    load_network_from_inp,
    translate_valve_to_surrogate,
)
from .network import Network
from .network_io import load_network_from_json
from .pump_affinity import pump_head_gain
from .residuals import mass_residual, pipe_energy_residual, pump_energy_residual
from .solver import (
    assemble_jacobian_analytic,
    assemble_residuals,
    assemble_residuals_batched,
    initial_guess,
    newton_solve,
    residual_norm,
)
from .shadow_replay import (
    ShadowReplayDataset,
    ShadowReplayDiagnostics,
    ShadowReplayFrame,
    build_shadow_replay_dataset,
    load_shadow_replay_csv,
)
from .telemetry_tag_map import (
    CanonicalTelemetryTag,
    TELEMETRY_AXES,
    TELEMETRY_AXIS_EDGE_FLOW,
    TELEMETRY_AXIS_EDGE_POWER,
    TELEMETRY_AXIS_EDGE_PUMP_SPEED,
    TELEMETRY_AXIS_EDGE_STATUS,
    TELEMETRY_AXIS_EDGE_VALVE_POSITION,
    TELEMETRY_AXIS_NODE_DEMAND,
    TELEMETRY_AXIS_NODE_LEVEL,
    TELEMETRY_AXIS_NODE_PRESSURE,
    TELEMETRY_AXIS_NODE_STATUS,
    TELEMETRY_MEASUREMENTS,
    TELEMETRY_MEASUREMENT_DEMAND,
    TELEMETRY_MEASUREMENT_FLOW,
    TELEMETRY_MEASUREMENT_LEVEL,
    TELEMETRY_MEASUREMENT_POWER,
    TELEMETRY_MEASUREMENT_PRESSURE,
    TELEMETRY_MEASUREMENT_PUMP_SPEED,
    TELEMETRY_MEASUREMENT_STATUS,
    TELEMETRY_MEASUREMENT_VALVE_POSITION,
    TELEMETRY_ROLES,
    TELEMETRY_ROLE_CONTROL_INPUT,
    TELEMETRY_ROLE_DERIVED,
    TELEMETRY_ROLE_OBSERVED,
    TELEMETRY_ROLE_QUALITY,
    TELEMETRY_TARGET_EDGE,
    TELEMETRY_TARGET_NODE,
    TELEMETRY_TARGET_TYPES,
    TelemetryTagMap,
    TelemetryTagMapDiagnostics,
    TelemetryTagSpec,
    build_telemetry_tag_map,
    load_telemetry_tag_map_json,
)

__all__ = [
    "assemble_jacobian_analytic",
    "assemble_residuals",
    "assemble_residuals_batched",
    "assert_finite_gradients",
    "cached_incidence_matrix",
    "classify_failure",
    "EDGE_SURROGATE_KIND_PRV_FIXED_HEAD",
    "EDGE_SURROGATE_KIND_TCV_MINOR_LOSS",
    "EDGE_SURROGATE_SEVERITY_INFO",
    "EDGE_SURROGATE_SEVERITY_LIMITATION",
    "EDGE_SURROGATE_SEVERITY_WARNING",
    "EpanetControlKind",
    "EpanetControlRuleDiagnostic",
    "EpanetEdgeSurrogateDiagnostic",
    "EpanetEmitterDemandDiagnostic",
    "EpanetIgnoredSectionDiagnostic",
    "EpanetImportDiagnostics",
    "EpanetImportDiagnosticsSummary",
    "EpanetImportQualityReport",
    "EpanetImportQualitySectionReport",
    "EpanetImportQualitySurrogateReport",
    "EpanetPatternEnergyDiagnostic",
    "EpanetStatusDiagnostic",
    "EpanetWaterQualityDiagnostic",
    "FeasibilityResult",
    "build_import_quality_report",
    "check_feasibility",
    "hazen_williams_head_loss",
    "fit_power_pump_surrogate",
    "fit_pump_head_curve",
    "fit_tcv_resistance_surrogate",
    "incidence_matrix",
    "initial_guess",
    "load_inp_diagnostics",
    "load_inp_import_quality_report",
    "load_network_from_inp",
    "load_network_from_json",
    "make_branch_network",
    "make_grid_network",
    "make_pump_network",
    "make_single_loop_network",
    "mass_residual",
    "Network",
    "newton_solve",
    "node_flow_balance",
    "pipe_energy_residual",
    "pump_energy_residual",
    "pump_head_gain",
    "residual_norm",
    "ShadowReplayDataset",
    "ShadowReplayDiagnostics",
    "ShadowReplayFrame",
    "SolveFailureReason",
    "SolveResult",
    "build_shadow_replay_dataset",
    "load_shadow_replay_csv",
    "CanonicalTelemetryTag",
    "TELEMETRY_AXES",
    "TELEMETRY_AXIS_EDGE_FLOW",
    "TELEMETRY_AXIS_EDGE_POWER",
    "TELEMETRY_AXIS_EDGE_PUMP_SPEED",
    "TELEMETRY_AXIS_EDGE_STATUS",
    "TELEMETRY_AXIS_EDGE_VALVE_POSITION",
    "TELEMETRY_AXIS_NODE_DEMAND",
    "TELEMETRY_AXIS_NODE_LEVEL",
    "TELEMETRY_AXIS_NODE_PRESSURE",
    "TELEMETRY_AXIS_NODE_STATUS",
    "TELEMETRY_MEASUREMENTS",
    "TELEMETRY_MEASUREMENT_DEMAND",
    "TELEMETRY_MEASUREMENT_FLOW",
    "TELEMETRY_MEASUREMENT_LEVEL",
    "TELEMETRY_MEASUREMENT_POWER",
    "TELEMETRY_MEASUREMENT_PRESSURE",
    "TELEMETRY_MEASUREMENT_PUMP_SPEED",
    "TELEMETRY_MEASUREMENT_STATUS",
    "TELEMETRY_MEASUREMENT_VALVE_POSITION",
    "TELEMETRY_ROLES",
    "TELEMETRY_ROLE_CONTROL_INPUT",
    "TELEMETRY_ROLE_DERIVED",
    "TELEMETRY_ROLE_OBSERVED",
    "TELEMETRY_ROLE_QUALITY",
    "TELEMETRY_TARGET_EDGE",
    "TELEMETRY_TARGET_NODE",
    "TELEMETRY_TARGET_TYPES",
    "TelemetryTagMap",
    "TelemetryTagMapDiagnostics",
    "TelemetryTagSpec",
    "build_telemetry_tag_map",
    "load_telemetry_tag_map_json",
    "translate_valve_to_surrogate",
]
